PROJECTDIRS += src
VPATH += src

CONTIKI_PROJECT = battery_server battery_client
all: $(CONTIKI_PROJECT)

# Use an absolute path to the Contiki-NG installation
CONTIKI = /opt/contiki-ng

# Include the standard Contiki-NG build rules
include $(CONTIKI)/Makefile.include
